[project]
site_name = "UoA Research AI GPU Platform"
url = "https://drai-inn.github.io/uoa-ai-gpu-docs/"

[repo]
url = "https://github.com/drai-inn/uoa-ai-gpu-docs"
name = "drai-inn/uoa-ai-gpu-docs"
edit_uri = "edit/main/docs/"

[nav]
Home = "index.md"
Guides = "guides/"
Platform = "platform/"
Reference = "reference/"

[theme]
name = "zensical"
logo = "assets/ake-uoa-k8s-party.gif"
favicon = "assets/ake-uoa-k8s-party.gif"
extra_css = ["stylesheets/extra.css"]

[project.theme]
features = [
    "navigation.tabs",
    "navigation.sections",
    "navigation.top",
    "navigation.footer",
    "search.suggest",
    "search.highlight",
    "content.code.copy"
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.font]
text = "Inter"
code = "Jetbrains Mono"

[copyright]
text = """
Copyright &copy; 2025 The University of Auckland<br>
<a href="https://www.auckland.ac.nz/en/admin/footer-links/disclaimer.html" target="_blank" rel="noopener">Disclaimer</a> &nbsp;|&nbsp;
<a href="https://www.auckland.ac.nz/en/privacy.html" target="_blank" rel="noopener">Privacy</a> &nbsp;|&nbsp;
<a href="https://www.auckland.ac.nz/en/accessibility.html" target="_blank" rel="noopener">Accessibility</a> &nbsp;|&nbsp;
<a href="https://uoaprod.service-now.com/sp?id=sc_cat_item&table=sc_cat_item&sys_id=563dedfadbaa3410e836be37f496197f" target="_blank" rel="noopener">Feedback</a>
"""

[[project.theme.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/drai-inn/uoa-ai-gpu-docs"
name = "GitHub"

[[project.theme.social]]
icon = "fontawesome/solid/house"
link = "https://research-hub.auckland.ac.nz/subhub/research-software-and-computing"
name = "Research Software and Computing"

